fos_js_routing:
    routes_to_expose:
        - get_utilisateurs
        - get_profil
        - get_etapes
        - get_etape_ues
        - post_etape_ues
        - new_voeux
        - get_csrf_token
        - edit_voeux