# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 15
        UserBundle\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 15

    role_hierarchy: #Is wrapped by Entity: UserBundle:Role
        ROLE_SUPER_ADMIN: [ROLE_ENSEIGNANT, ROLE_RESP_SERVICE, ROLE_RESP_COMPTABLE]
        ROLE_INTERVENANT: ROLE_VISITEUR
        ROLE_ENSEIGNANT:  ROLE_INTERVENANT
        ROLE_RESP_UE: ROLE_VISITEUR
        ROLE_RESP_SERVICE: [ROLE_RESP_ETAPE, ROLE_RESP_UE]
        ROLE_RESP_ETAPE: ROLE_VISITEUR
        ROLE_RESP_COMPTABLE: ROLE_VISITEUR

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: UserBundle:Utilisateur
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: db_provider
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: Username
                password_parameter: Password
            logout:
                path: logout
                target: login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /


    access_control:
        - { path: ^/api/voeux/*, roles: [ROLE_ENSEIGNANT, ROLE_INTERVENANT] } #Seul les enseignants et ceux qui hérite du rôle peuvent acceder à une route rest pour update les voeux
        - { path: ^/app/intervenant/*, roles: [ROLE_ENSEIGNANT, ROLE_INTERVENANT] } #Seul les enseignants et ceux qui hérite du rôle peuvent acceder à une route du bundle enseignant
        - { path: ^/api/*, roles: [ROLE_VISITEUR, ROLE_ENSEIGNANT] }
        - { path: ^/app/*, roles: [ROLE_VISITEUR, ROLE_ENSEIGNANT] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }


