# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    jms_serializer.naming_strategy:
        class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
