<?php

namespace UserBundle\Repository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Query\Expr\Join;
use VisiteurBundle\Entity\Email;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsers() {
        $queryBuilder = $this->createQueryBuilder('u')->select('concat(u.nom, \' \',u.prenom) as display_name, u.id');
        return $queryBuilder->getQuery()->getResult();


    }

    public function testQueryBuilderPossibilities() {
        $qb = $this->createQueryBuilder('u')->select('u', 'e', 'n')->distinct(true)
            ->innerJoin('u.email_list', 'e')
            ->innerJoin('u.num_list', 'n')
        ;

        $query = $this->getEntityManager()->createQuery("SELECT utilisateurs_11 FROM UserBundle\Entity\Utilisateur utilisateurs_11 INNER JOIN utilisateurs_11.email_list mails_16 INNER JOIN utilisateurs_11.num_list numeros_19");
        return $query->getScalarResult();
    }
}
