utilisateurs:
    type:     "rest"
    host:     "localhost"
    resource: "@ApiBundle/Controller/UtilisateurController.php"

etapes:
    type:     "rest"
    host:     "localhost"
    resource: "@ApiBundle/Controller/EtapeController.php"
