utilisateurs:
    type:     "rest"
    host:     "localhost"
    resource: "@ApiBundle/Controller/UtilisateurController.php"

etapes:
    type:     "rest"
    host:     "localhost"
    resource: "@ApiBundle/Controller/EtapeController.php"


voeux:
    type:     "rest"
    host:     "localhost"
    resource: "@ApiBundle/Controller/VoeuxController.php"


csrf:
    type:     "rest"
    host:     "localhost"
    resource: "@ApiBundle/Controller/CsrfTokenController.php"
