utilisateurs:
    type:     "rest"
    host:     "localhost"
    resource: "@ApiBundle/Controller/UtilisateurController.php"

enseignements:
    type:     "rest"
    host:     "localhost"
    resource: "@ApiBundle/Controller/EnseignementsController.php"
