<?php

namespace IntervenantBundle\Repository;

/**
 * MissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends \Doctrine\ORM\EntityRepository
{
}
