<?php

namespace IntervenantBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\DependencyInjection\Container;
use UserBundle\Entity\Utilisateur;

/**
 * MissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends EntityRepository
{
	/**
     * @var Container;
     */
    private $container;


    public function getMissionsFilteredByName($name, $itemsByPage, $currentPage) {
        $qb = $this->createQueryBuilder('missions');

        $qb
            ->where($qb->expr()->like('missions.name', ':name'))
            ->setFirstResult(($currentPage - 1) * $itemsByPage)
            ->setMaxResults($currentPage * $itemsByPage)
            ->setParameter(':name', '%'.$name.'%')
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function getMissionsFromUser(Utilisateur $utilisateur){

        $composante = $utilisateur->getComposante();

        $queryBuilder = $this->createQueryBuilder('mission')->select('mission.id, mission.name')->where("mission.composante = :composante")->setParameter("composante", $composante);

        return $queryBuilder->getQuery()->getResult();
    }
}
