services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    listener.utilisateur:
        class: UserBundle\Entity\Listener\UtilisateurListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.orm.entity_listener }
