services:
    tools.excel.yaml.parser:
        class: ToolsBundle\Services\ExcelMappingParser\MappingParser
#    tools.example:
#        class: ToolsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
