visiteur_homepage:
    path:     /profil
    defaults: { _controller: VisiteurBundle:Profil:monProfil }

visiteur_profils:
    path:     /profils
    defaults: { _controller: VisiteurBundle:Default:consulterProfils }
visiteur_etat_annee:
    path:     /etat_annee
    defaults: { _controller: VisiteurBundle:Annee:etatAnnee }
