visiteur_homepage:
    path:     /profil
    defaults: { _controller: VisiteurBundle:Profil:monProfil }

visiteur_liste_enseignements:
    path:     /liste_enseignements
    defaults: { _controller: VisiteurBundle:ListeEnseignements:ListeEnseignements }

visiteur_profils:
    path:     /profils
    defaults: { _controller: VisiteurBundle:Profil:consulterProfils }
visiteur_etat_annee:
    path:     /etat_annee
    defaults: { _controller: VisiteurBundle:Annee:etatAnnee }
