services:
    app.twig_extension:
        class: VisiteurBundle\Twig\TwigExtension
        public: true
        tags:
            - { name: twig.extension }

    form.rechercher_utilisateur:
        class: VisiteurBundle\Form\RechercheUtilisateurForm
        arguments:
            - "@router"
        tags:
            - { name: form.type }