enseignant_homepage:
    path:     /
    defaults: { _controller: EnseignantBundle:Voeux:index }

enseignant_bilanVoeux:
    path:     /bilanVoeux
    defaults: { _controller: EnseignantBundle:Voeux:bilanVoeuxParComposante }