<?php
/**
 * Created by PhpStorm.
 * User: tanna
 * Date: 15/02/2017
 * Time: 15:31
 */

namespace UserBundle\Form;


use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CollectionType extends \Symfony\Component\Form\Extension\Core\Type\CollectionType
{
    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['attr']['allow-add'] = $options['allow_add'] ? 'true' : 'false';
        $view->vars['attr']['allow-delete'] = $options['allow_delete'] ? 'true' : 'false';
        parent::buildView($view, $form, $options);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);
        $resolver->setDefaults(array(
            'entry_options' => ['label' => false],
        ));

    }

    /**
     * {@inheritdoc}
     */
    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['prototype']->vars['attr']['collection-item'] = 'collection-item';
        foreach ($view->children as $child) {
            $child->vars['attr']['collection-item'] = 'collection-item';
        }

        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}