<?php

namespace VisiteurBundle\Repository;

/**
 * AnneeUniversitaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeUniversitaireRepository extends \Doctrine\ORM\EntityRepository
{
}
