<?php

namespace VisiteurBundle\Repository;

/**
 * ComposanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposanteRepository extends \Doctrine\ORM\EntityRepository
{
}
