<?php

namespace VisiteurBundle\Repository;

/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends \Doctrine\ORM\EntityRepository
{
    $tokenStorage;

    public function __construct(TokenStorage $token){
        $tokenStorage = $token;
    }

    public function getNames() {
        $queryBuilder = $this->createQueryBuilder('e')->select('e.name');
        $result = $queryBuilder->getQuery()->getResult();

        //obligé de passer par cette étape de conversion car typeahead.js ne permet pas l'autocomplétion d'objets
        $returnArray = [];
        foreach ($result as $etape_infos) {
            $returnArray[] = $etape_infos['name'];
        }

        return $returnArray;
    }

    public function getEtapesFromUser(){
        $user = $tokenStorage->getToken()->getUser();
        $composante = $user->getComposante();


    }

    public function findEtapeByName($data){
        $queryBuilder = $this->createQueryBuilder('e')->select('e.name');
        if($data['name'] != '')

        {

            $query->andWhere('e.name = :name')

                ->setParameter('name', $data['name']);

        }

    }
}
