<?php

namespace VisiteurBundle\Repository;

/**
 * EtatAnneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatAnneeRepository extends \Doctrine\ORM\EntityRepository
{
}
