<?php

namespace VisiteurBundle\Repository;

/**
 * NumeroTelephoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeroTelephoneRepository extends \Doctrine\ORM\EntityRepository
{
}
