<?php

namespace VisiteurBundle\Repository;

/**
 * UERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UERepository extends \Doctrine\ORM\EntityRepository
{
}
