<?php

namespace VisiteurBundle\Repository;

/**
 * UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
}
