<?php

namespace VisiteurBundle\Repository;

/**
 * UtilNotifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilNotifRepository extends \Doctrine\ORM\EntityRepository
{
}
