<?php

namespace VisiteurBundle\Repository;

/**
 * VoeuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoeuxRepository extends \Doctrine\ORM\EntityRepository
{
}
